Update playlist.py
to avoid string error

```bash
Traceback (most recent call last):
  File "playlist.py", line 182, in <module>
    main()
  File "playlist.py", line 170, in main
    findCommonTracks(args.plFiles)
  File "playlist.py", line 50, in findCommonTracks
    f.write(s.encode("UTF-8"))
TypeError: must be str, not bytes
```

need to write 'wb' now instead of just 'w'